// Regenerates src/teletext/glyphs.ts from the Bedstead font.
//
// Bedstead (https://bjh21.me.uk/bedstead/) by Ben Harris recreates the SAA5050
// teletext character generator, including its diagonal "character rounding".
// It is dedicated to the public domain (CC0-1.0). We ship its outlines as SVG
// path data so the cards need no web font: every glyph is a <path> that renders
// the same in every browser.
//
// Usage: npm run glyphs

import { readFileSync, writeFileSync } from 'node:fs';
import opentype from 'opentype.js';

const FONT = new URL('../vendor/bedstead.otf', import.meta.url);
const OUT = new URL('../src/teletext/glyphs.ts', import.meta.url);

// Bedstead draws a 6x10 pixel cell as 600x1000 font units with the baseline
// 200 units above the bottom. We store paths in teletext pixels, y down.
const UNIT = 100;
const ASCENT = 800;

const ranges: Array<[number, number]> = [
  [0x20, 0x7e], // ASCII
  [0xa1, 0xff], // Latin-1: æøå, éü, ½, ©, ...
];
const extras = '‘’“”–—…•←→↑↓€™★☆♥●○■□▲▼►◄✓✗';

const wanted: string[] = [];
for (const [from, to] of ranges) {
  for (let cp = from; cp <= to; cp++) {
    if (cp === 0xad) continue; // soft hyphen
    wanted.push(String.fromCodePoint(cp));
  }
}
for (const ch of extras) if (!wanted.includes(ch)) wanted.push(ch);

const buf = readFileSync(FONT);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

function num(v: number): string {
  const s = String(Math.round(v * 100) / 100);
  return s.startsWith('0.') ? s.slice(1) : s.startsWith('-0.') ? `-${s.slice(2)}` : s;
}

function join(cmd: string, values: number[]): string {
  let out = cmd;
  let prev = '';
  for (const v of values) {
    const s = num(v);
    // A separator is only needed where the next number could merge with the previous one.
    const merges = prev !== '' && !s.startsWith('-') && !(s.startsWith('.') && prev.includes('.'));
    out += (merges ? ' ' : '') + s;
    prev = s;
  }
  return out;
}

function toPath(ch: string): string | null {
  const glyph = font.charToGlyph(ch);
  if (!glyph || glyph.index === 0) return null;
  let d = '';
  let x = 0;
  let y = 0;
  for (const c of glyph.path.commands) {
    if (c.type === 'Z') {
      d += 'Z';
      continue;
    }
    const nx = c.x / UNIT;
    const ny = (ASCENT - c.y) / UNIT;
    if (c.type === 'M') d += join('M', [nx, ny]);
    else if (c.type === 'L') {
      if (ny === y) d += join('H', [nx]);
      else if (nx === x) d += join('V', [ny]);
      else d += join('L', [nx, ny]);
    } else if (c.type === 'Q') {
      d += join('Q', [c.x1 / UNIT, (ASCENT - c.y1) / UNIT, nx, ny]);
    } else if (c.type === 'C') {
      d += join('C', [c.x1 / UNIT, (ASCENT - c.y1) / UNIT, c.x2 / UNIT, (ASCENT - c.y2) / UNIT, nx, ny]);
    }
    x = nx;
    y = ny;
  }
  return d;
}

const entries: string[] = [];
const missing: string[] = [];
for (const ch of wanted) {
  const d = toPath(ch);
  if (d === null) missing.push(ch);
  else entries.push(`  ${JSON.stringify(ch)}: ${JSON.stringify(d)},`);
}

const source = `// Generated by scripts/build-glyphs.ts from Bedstead by Ben Harris
// (https://bjh21.me.uk/bedstead/), dedicated to the public domain (CC0-1.0).
// Do not edit by hand: run \`npm run glyphs\`.
//
// Each path fills one 6x10 teletext cell, in teletext pixels with y pointing down.

export const GLYPHS: Readonly<Record<string, string>> = {
${entries.join('\n')}
};
`;

writeFileSync(OUT, source);
console.log(`wrote ${entries.length} glyphs to ${OUT.pathname}`);
if (missing.length) console.log(`not in Bedstead, skipped: ${missing.join(' ')}`);
